/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 69bbd9e40030b4863f76f001f2902335)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEVICE_TOKENS: string;
	SESSION_SECRET: string;
	ICE_SERVERS_JSON: string;
	TURN_KEY_ID: string;
	TURN_KEY_API_TOKEN: string;
	ROOMS: DurableObjectNamespace<import("./src/index").VideoRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VideoRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEVICE_TOKENS" | "SESSION_SECRET" | "ICE_SERVERS_JSON" | "TURN_KEY_ID" | "TURN_KEY_API_TOKEN">> {}
}
