/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6ab9b6f272fb796331816c23cdef3db9)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ROOMS: DurableObjectNamespace<import("./src/index").VideoRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VideoRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
