plugins { id 'com.android.application' }

android {
    namespace 'jp.stepkobetsu.classroomvideo'
    compileSdk 35
    defaultConfig {
        applicationId 'jp.stepkobetsu.classroomvideo'
        minSdk 22
        targetSdk 28
        versionCode 2
        versionName '0.1.1-fire'
        buildConfigField 'String', 'APP_URL', '"https://step-classroom-video.stepkobetsu.workers.dev/"'
    }
    buildFeatures { buildConfig true }
}
