/* Search aliases for names used in the STEP registry. Keep the original text searchable too. */
const registrySearch=(()=>{
  const readings={
    '生徒':'せいと','塾生':'じゅくせい','生徒マスタ':'せいとますた','生徒情報':'せいとじょうほう','生徒名簿':'せいとめいぼ','検索':'けんさく','登録':'とうろく','講師':'こうし','先生':'せんせい','授業':'じゅぎょう','報告':'ほうこく','成績':'せいせき','管理':'かんり','進捗':'しんちょく','出退':'しゅったい','入退室':'にゅうたいしつ','出席':'しゅっせき','欠席':'けっせき','連絡':'れんらく','請求':'せいきゅう','経理':'けいり','会計':'かいけい','給与':'きゅうよ','振替':'ふりかえ','口座':'こうざ','名札':'なふだ','教室':'きょうしつ','神領':'じんりょう','大手町':'おおてまち','神領校':'じんりょうこう','大手町校':'おおてまちこう','予定':'よてい','時間割':'じかんわり','印刷':'いんさつ','発行':'はっこう','配信':'はいしん','通知':'つうち','送信':'そうしん','返信':'へんしん','住所':'じゅうしょ','受付':'うけつけ','事務':'じむ','面談':'めんだん','懇談':'こんだん','日程':'にってい','変更':'へんこう','作成':'さくせい','一覧':'いちらん','教材':'きょうざい','英単語':'えいたんご','英語':'えいご','数学':'すうがく','国語':'こくご','理科':'りか','社会':'しゃかい','試験':'しけん','模試':'もし','受験票':'じゅけんひょう','学習':'がくしゅう','保護者':'ほごしゃ','児童':'じどう','入塾':'にゅうじゅく','退塾':'たいじゅく','生年月日':'せいねんがっぴ','資産':'しさん','台帳':'だいちょう','証憑':'しょうひょう','集金':'しゅうきん','月謝':'げっしゃ','請求書':'せいきゅうしょ','領収書':'りょうしゅうしょ','自動':'じどう','更新':'こうしん','設定':'せってい','履歴':'りれき','公式':'こうしき','業務':'ぎょうむ','情報':'じょうほう','出退くん':'しゅったいくん','塾長':'じゅくちょう','個別指導':'こべつしどう','学年':'がくねん','小学生':'しょうがくせい','中学生':'ちゅうがくせい','高校生':'こうこうせい','放課後':'ほうかご','管理者':'かんりしゃ','スタッフ':'すたっふ','カード':'かーど','アプリ':'あぷり','システム':'しすてむ','ポータル':'ぽーたる','カレンダー':'かれんだー','ポイント':'ぽいんと','マスター':'ますたー','マスタ':'ますた','フォーム':'ふぉーむ','ホーム':'ほーむ','メール':'めーる','ライン':'らいん','プリント':'ぷりんと','フォレスタ':'ふぉれすた','ステップ':'すてっぷ','ゴール':'ごーる','デジタル':'でじたる','書類':'しょるい','写真':'しゃしん','取込':'とりこみ','読取':'よみとり','読み取り':'よみとり','検索窓':'けんさくまど'
  };
  const terms=Object.keys(readings).sort((a,b)=>b.length-a.length);
  const readingPattern=new RegExp(terms.join('|'),'g');
  const romaji={kya:'きゃ',kyu:'きゅ',kyo:'きょ',sha:'しゃ',shu:'しゅ',sho:'しょ',sya:'しゃ',syu:'しゅ',syo:'しょ',cha:'ちゃ',chu:'ちゅ',cho:'ちょ',tya:'ちゃ',tyu:'ちゅ',tyo:'ちょ',nya:'にゃ',nyu:'にゅ',nyo:'にょ',hya:'ひゃ',hyu:'ひゅ',hyo:'ひょ',mya:'みゃ',myu:'みゅ',myo:'みょ',rya:'りゃ',ryu:'りゅ',ryo:'りょ',gya:'ぎゃ',gyu:'ぎゅ',gyo:'ぎょ',ja:'じゃ',ju:'じゅ',jo:'じょ',jya:'じゃ',jyu:'じゅ',jyo:'じょ',bya:'びゃ',byu:'びゅ',byo:'びょ',pya:'ぴゃ',pyu:'ぴゅ',pyo:'ぴょ',shi:'し',chi:'ち',tsu:'つ',fu:'ふ',si:'し',ti:'ち',tu:'つ',hu:'ふ',fa:'ふぁ',fi:'ふぃ',fe:'ふぇ',fo:'ふぉ',va:'ゔぁ',vi:'ゔぃ',vu:'ゔ',ve:'ゔぇ',vo:'ゔぉ',wi:'うぃ',we:'うぇ',ka:'か',ki:'き',ku:'く',ke:'け',ko:'こ',sa:'さ',su:'す',se:'せ',so:'そ',ta:'た',te:'て',to:'と',na:'な',ni:'に',nu:'ぬ',ne:'ね',no:'の',ha:'は',hi:'ひ',he:'へ',ho:'ほ',ma:'ま',mi:'み',mu:'む',me:'め',mo:'も',ya:'や',yu:'ゆ',yo:'よ',ra:'ら',ri:'り',ru:'る',re:'れ',ro:'ろ',wa:'わ',wo:'を',ga:'が',gi:'ぎ',gu:'ぐ',ge:'げ',go:'ご',za:'ざ',ji:'じ',zi:'じ',zu:'ず',ze:'ぜ',zo:'ぞ',da:'だ',di:'ぢ',du:'づ',de:'で',do:'ど',ba:'ば',bi:'び',bu:'ぶ',be:'べ',bo:'ぼ',pa:'ぱ',pi:'ぴ',pu:'ぷ',pe:'ぺ',po:'ぽ',a:'あ',i:'い',u:'う',e:'え',o:'お'};
  const normalize=value=>String(value??'').toLowerCase().normalize('NFKC').replace(/[\s　]+/g,'').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96)).replace(/ー/g,'');
  function reading(value){return normalize(value).replace(readingPattern,term=>readings[term]);}
  function toKana(value){const input=normalize(value);return input.replace(/[a-z]+/g,segment=>{let out='';for(let i=0;i<segment.length;){if(segment[i]==='n'&&(i===segment.length-1||segment[i+1]==='n'||!/[aiueoy]/.test(segment[i+1]))){out+='ん';i+=segment[i+1]==='n'?2:1;continue}if(segment[i]===segment[i+1]&&/[bcdfghjklmpqrstvwxyz]/.test(segment[i])&&segment[i]!=='n'){out+='っ';i++;continue}let found=false;for(const length of [3,2,1]){const kana=romaji[segment.slice(i,i+length)];if(kana){out+=kana;i+=length;found=true;break}}if(!found){out+=segment[i];i++}}return out});}
  function matches(source,query){const words=String(query??'').trim().split(/[\s　]+/).map(normalize).filter(Boolean);if(!words.length)return true;const raw=normalize(source);let phonetic;return words.every(q=>{if(raw.includes(q))return true;phonetic??=reading(source);const queryReading=reading(q);return phonetic.includes(toKana(queryReading))||phonetic.includes(queryReading);});}
  return {matches,normalize,reading,toKana};
})();
if(typeof module!=='undefined')module.exports=registrySearch;
